// data.js

export const names = {
  ghana: [
    "Yaw Ansah", "Ama Mensah", "Kwame Nkrumah", "Akua Asantewaa", "Kofi Annan",
    "Adwoa Sarfo", "Kwabena Boateng", "Afia Osei", "Kwaku Duah", "Abena Nsiah",
    "Yaw Frempong", "Ama Serwaa", "Kojo Agyemang", "Yaa Konadu", "Kwasi Appiah",
    "Akosua Darko", "Obed Owusu", "Theresa Opoku", "Mensa Adjei", "Araba Sey",
    "Kofi Baah", "Adwoa Mansah", "Kwabena Acheampong", "Afia Gyimah", "Kwaku Bonsu",
    "Abena Dapaah", "Yaw Danso", "Ama Kyerewaa", "Kojo Antwi", "Yaa Boatemaa",
    "Kwasi Nimo", "Akosua Addo", "Emmanuel Amoah", "Augustina Owusu", "Dennis Ofori",
    "Joyce Asare", "Richard Oppong", "Victoria Kyeremateng", "Samuel Adu", "Elizabeth Frimpong",
    "Ebenezer Agyei", "Gladys Mensah", "Justice Boakye", "Mary Appiah", "Maxwell Osei",
    "Dora Ampofo", "George Nkrumah", "Faustina Obeng", "Daniel Amponsah", "Hannah Acquah",
    "Michael Danso", "Patricia Gyasi", "Eric Koranteng", "Rosemary Nkansah", "Joseph Yeboah",
    "Monica Baffour", "David Asante", "Grace Akoto", "Stephen Osei-Tutu", "Felicia Nsiah",
    "Frank Kwakye", "Dorcas Agyeiwaa", "Philip Antwi", "Lydia Owusu-Ansah", "John Koomson",
    "Esther Amoako", "Peter Adjei", "Rebecca Nkansah", "Paul Obeng", "Ruth Opare",
    "Fredrick Owusu", "Priscilla Asamoah", "Isaac Nketia", "Alberta Mensah", "Joshua Adomako",
    "Mercy Sarfo", "Benjamin Gyamera", "Georgina Konadu", "Alfred Quansah", "Florence Nyarko",
    "Bright Addo", "Portia Amponsah", "Chris Annan", "Gifty Ofori", "Prosper Acheampong",
    "Salome Asare", "Patrick Opoku", "Stella Donkor", "Abraham Nkansah", "Victoria Boateng",
    "Vincent Kyeremeh", "Sophia Mensah", "Emmanuel Agyenim-Boateng", "Juliana Darko", "Godfred Sarfo",
    "Christiana Ampofo", "Jeffrey Owusu", "Beatrice Osei", "Nathaniel Adjei", "Gloria Frimpong"
  ],
  nigeria: [
    "Chinedu Emeka", "Ada Oghenemaro", "Segun Adebayo", "Fatima Abdullahi", "Obi Okoro",
    "Amaka Eze", "Tunde Olawale", "Zainab Musa", "Lekan Owolabi", "Nkechi Ibe",
    "Kunle Alabi", "Aisha Abubakar", "Emeka Okonkwo", "Chioma Nnadi", "Adeola Balogun",
    "Sade Akinwumi", "Chukwudi Ezeh", "Ify Okoroafor", "Mohammed Bello", "Maryam Ibrahim",
    "Ibrahim Audu", "Bimpe Adewale", "Ahmed Yusuf", "Hadiza Sani", "Kelechi Nnamani",
    "Funke Adekunle", "Umar Farouk", "Halima Usman", "Ngozi Okafor", "Dapo Ojo",
    "Blessing Oladipo", "Jide Bankole", "Toyin Ayodele", "Tope Adeoye", "Chidimma Okeke",
    "Gabriel Uche", "Grace Omoniyi", "Victor Onyeka", "Joy Okoro", "Daniel Ayodele",
    "Sarah Chukwu", "Michael Obi", "Blessing Okon", "Joseph Dada", "Esther Ezeudu",
    "David Okorocha", "Faith Ebere", "Samuel Adeyemi", "Precious Adeyemi", "Peter Okoye",
    "Rosemary Eke", "Paul Eze", "Comfort Idowu", "Stephen Onyekachi", "Favour Adewale",
    "Franklyn Nwafor", "Peace Anyanwu", "Philip Ugochukwu", "Mercy Okeke", "John Akpan",
    "Victoria Ekeinde", "Patrick Ezeani", "Blessing Samuel", "Isaac Olawole", "Lydia Adebayo",
    "Joshua Madu", "Chinwe Eze", "Benjamin Chukwu", "Gloria Obinna", "Alfred Nwafor",
    "Florence Akinwumi", "Bright Okeke", "Priscilla Okafor", "Chris Ifeanyi", "Gifty Musa",
    "Prosper Obi", "Salome Eze", "Patrick Obinna", "Stella Nwosu", "Abraham Adewale",
    "Victoria Okorie", "Vincent Nnamdi", "Sophia Ojo", "Emmanuel Okoro", "Juliana Emeka",
    "Godfrey Ezeudu", "Christiana Onyeka", "Jeffrey Duru", "Beatrice Adeoye", "Nathaniel Chukwuma",
    "Gloria Olawale", "Festus Okoro", "Oluwafemi Adekunle", "Vivian Okeke", "Toluwani Adebayo",
    "Francis Okeke", "Damilola Oyewole", "Divine Akpan", "Chioma Ezeala", "Femi Adebisi"
  ]
};

export const bios = {
  ghana: [
    "Loves waakye and slow jams.",
    "Always ready for a good fufu meal.",
    "Passionate about Ghanaian music and highlife.",
    "Enjoys beach sunsets in Accra.",
    "Known for a great sense of humor.",
    "A proud supporter of the Black Stars.",
    "Finds joy in community gatherings.",
    "Loves to share stories and laughter.",
    "Keen on exploring local markets.",
    "A fan of traditional kente cloth.",
    "Always has time for family.",
    "Enjoys a refreshing glass of bissap.",
    "Passionate about education.",
    "Loves to dance to afrobeats.",
    "Finds peace by the ocean.",
    "A keen observer of daily life.",
    "Enjoys a good debate.",
    "Loves to cook hearty Ghanaian meals.",
    "Always has a friendly smile.",
    "Passionate about local craftsmanship.",
    "Finds beauty in everyday moments.",
    "Enjoys the bustling energy of the city.",
    "A connoisseur of street food.",
    "Loves to travel within Ghana.",
    "Always learning new things.",
    "Enjoys quiet evenings at home.",
    "Passionate about sustainable living.",
    "Finds inspiration in nature.",
    "A lover of art and culture.",
    "Enjoys historical storytelling.",
    "Loves to spend time with friends.",
    "Always dressed sharply.",
    "Enjoys a good laugh over palm wine.",
    "Passionate about entrepreneurship.",
    "Finds strength in community.",
    "A supporter of local businesses.",
    "Enjoys a good game of draughts.",
    "Loves to visit the villages.",
    "Always ready to lend a hand.",
    "Enjoys a refreshing coconut.",
    "Passionate about social justice.",
    "Finds joy in simple pleasures.",
    "A lover of Ghanaian proverbs.",
    "Enjoys a walk through the market.",
    "Loves to sing along to gospel music.",
    "Always ready for an adventure.",
    "Enjoys the warmth of the sun.",
    "Passionate about local fashion.",
    "Finds peace in quiet reflection.",
    "A champion of positive vibes.",
    "Enjoys the sound of crashing waves.",
    "Loves to connect with new people.",
    "Always appreciative of good company.",
    "Enjoys a good plate of jollof.",
    "Passionate about youth development.",
    "Finds happiness in sharing.",
    "A lover of vibrant colors.",
    "Enjoys a refreshing drink with friends.",
    "Loves to explore new places.",
    "Always curious and eager to learn.",
    "Enjoys the rhythm of daily life.",
    "Passionate about preserving culture.",
    "Finds comfort in tradition.",
    "A keen gardener.",
    "Enjoys reading and contemplation.",
    "Loves to capture moments with a camera.",
    "Always seeking new experiences.",
    "Enjoys a good football match.",
    "Passionate about healthy living.",
    "Finds joy in creative pursuits.",
    "A lover of natural beauty.",
    "Enjoys the fresh air.",
    "Loves to solve puzzles.",
    "Always optimistic.",
    "Enjoys the sounds of the city.",
    "Passionate about technology.",
    "Finds motivation in challenges.",
    "A strong advocate for change.",
    "Enjoys a peaceful morning.",
    "Loves to learn new languages.",
    "Always supportive of others.",
    "Enjoys a quiet cup of tea.",
    "Passionate about history.",
    "Finds wonder in everyday life.",
    "A person of strong convictions.",
    "Enjoys a good long walk.",
    "Loves to share laughter with loved ones.",
    "Always has a story to tell.",
    "Enjoys the aroma of freshly cooked food.",
    "Passionate about environmental causes.",
    "Finds inspiration in resilience.",
    "A true friend.",
    "Enjoys the simplicity of life.",
    "Loves to offer advice.",
    "Always willing to listen.",
    "Enjoys the vibrant energy of festivals.",
    "Passionate about human connection.",
    "Finds peace in quiet moments.",
    "A thoughtful individual."
  ],
  nigeria: [
    "Loves jollof and good vibes.",
    "Always ready for a lively discussion.",
    "Passionate about Nigerian movies (Nollywood).",
    "Enjoys bustling city life in Lagos.",
    "Known for strong opinions and a warm heart.",
    "A proud supporter of the Super Eagles.",
    "Finds joy in family celebrations.",
    "Loves to tell captivating stories.",
    "Keen on discovering new music.",
    "A fan of vibrant Ankara prints.",
    "Always puts family first.",
    "Enjoys a cold bottle of Chapman.",
    "Passionate about innovation.",
    "Loves to dance to afrobeats.",
    "Finds peace in spiritual reflection.",
    "A keen business mind.",
    "Enjoys a good laugh with friends.",
    "Loves to cook delicious Nigerian dishes.",
    "Always generous and welcoming.",
    "Passionate about local artistry.",
    "Finds beauty in diversity.",
    "Enjoys the energetic pace of the market.",
    "A connoisseur of spicy food.",
    "Loves to explore new states.",
    "Always expanding their knowledge.",
    "Enjoys lively evenings out.",
    "Passionate about social impact.",
    "Finds strength in collective effort.",
    "A lover of witty banter.",
    "Enjoys historical narratives.",
    "Loves to spend time with loved ones.",
    "Always well-dressed.",
    "Enjoys a good game of Ludo.",
    "Passionate about community development.",
    "Finds comfort in tradition.",
    "A supporter of emerging talent.",
    "Enjoys a good read.",
    "Loves to visit hometowns.",
    "Always willing to help.",
    "Enjoys a refreshing kunu.",
    "Passionate about justice.",
    "Finds joy in acts of kindness.",
    "A lover of Nigerian folklore.",
    "Enjoys a stroll through urban parks.",
    "Loves to sing along to praise and worship.",
    "Always seeking adventure.",
    "Enjoys the warmth of camaraderie.",
    "Passionate about fashion trends.",
    "Finds peace in solitude.",
    "A champion of optimism.",
    "Enjoys the sounds of celebration.",
    "Loves to engage in deep conversations.",
    "Always valuing loyalty.",
    "Enjoys a hearty plate of pounded yam.",
    "Passionate about empowering youth.",
    "Finds happiness in giving.",
    "A lover of bold statements.",
    "Enjoys a good discussion over a drink.",
    "Loves to visit cultural sites.",
    "Always open-minded.",
    "Enjoys the hustle and bustle.",
    "Passionate about cultural heritage.",
    "Finds comfort in family bonds.",
    "A natural leader.",
    "Enjoys quiet moments of reflection.",
    "Loves to document experiences.",
    "Always ready for a challenge.",
    "Enjoys a good football match.",
    "Passionate about fitness.",
    "Finds joy in creating.",
    "A lover of vibrant street art.",
    "Enjoys the fresh breeze.",
    "Loves to tell jokes.",
    "Always resilient.",
    "Enjoys the rhythm of the drums.",
    "Passionate about entrepreneurship.",
    "Finds motivation in success.",
    "A strong voice for progress.",
    "Enjoys a peaceful dawn.",
    "Loves to learn about different cultures.",
    "Always there for friends.",
    "Enjoys a good cup of coffee.",
    "Passionate about personal growth.",
    "Finds wonder in everyday achievements.",
    "A person of integrity.",
    "Enjoys a good long drive.",
    "Loves to share wisdom.",
    "Always a source of encouragement.",
    "Enjoys the aroma of freshly brewed tea.",
    "Passionate about environmental sustainability.",
    "Finds inspiration in overcoming obstacles.",
    "A loyal companion.",
    "Enjoys the simple beauty of life.",
    "Loves to inspire others.",
    "Always ready to uplift.",
    "Enjoys the vibrant energy of carnivals.",
    "Passionate about building bridges.",
    "Finds peace in strong connections.",
    "A thoughtful and kind soul."
  ]
};

export const jobTitles = {
    ghana: [
        "UX Designer",
        "UI Designer",
        "Frontend Developer",
        "Backend Developer",
        "Fullstack Developer",
        "Product Designer",
        "Data Analyst",
        "Data Scientist",
        "Mobile App Developer",
        "DevOps Engineer",
        "AI Engineer",
        "Machine Learning Engineer",
        "Graphic Designer",
        "Visual Designer",
        "Creative Director",
        "Marketing Specialist",
        "Content Strategist",
        "SEO Analyst",
        "Software Engineer",
        "QA Engineer",
        "Cloud Architect",
        "Database Administrator",
        "Web Developer",
        "Technical Writer",
        "IT Support Specialist",
        "Scrum Master",
        "Project Manager",
        "Product Manager",
        "Systems Analyst",
        "Security Analyst",
        "Solutions Architect",
        "AR/VR Designer",
        "Video Editor",
        "Brand Designer",
        "Motion Designer",
        "Business Analyst",
        "Game Developer",
        "CRM Specialist",
        "eCommerce Manager",
        "Community Manager",
        "UX Researcher",
        "HR Manager",
        "Recruiter",
        "Digital Marketer",
        "Social Media Manager",
        "Creative Technologist",
        "Innovation Lead",
        "Technical Lead",
        "Customer Support Engineer",
        "Technical Account Manager",
        "Design Systems Lead",
        "Accessibility Specialist",
        "Penetration Tester",
        "Cloud Security Engineer",
        "SRE (Site Reliability Engineer)",
        "Network Engineer",
        "Blockchain Developer",
        "Embedded Systems Engineer",
        "Animation Specialist",
        "VR Developer",
        "3D Modeler",
        "Legal Consultant",
        "AI Prompt Engineer",
        "IT Auditor",
        "Cybersecurity Specialist",
        "Helpdesk Agent",
        "Platform Engineer",
        "No-code Developer",
        "Low-code Developer",
        "Game Tester",
        "Unity Developer",
        "Unreal Developer",
        "Firmware Engineer",
        "Simulation Engineer",
        "Creative Producer",
        "Growth Marketer",
        "UX Copywriter",
        "Brand Strategist",
        "Innovation Consultant",
        "Quality Assurance Tester",
        "Customer Success Manager",
        "Support Analyst",
        "Interaction Designer",
        "Storyteller",
        "Frontend Architect",
        "Digital Illustrator",
        "Infographic Designer",
        "Technical Evangelist",
        "UI Engineer",
        "API Developer",
        "Design Educator",
        "Webflow Developer",
        "Notion Specialist",
        "Chatbot Designer",
        "Prompt Designer",
        "Generative AI Designer",
        "Web3 Developer",
        "Smart Contract Developer",
        "Figma Plugin Developer",
        "AI Trainer",
        "Voice UX Designer",
        "Creative Coder",
        "Product Illustrator",
    ],
    nigeria: [
        "UX Designer",
        "UI Designer",
        "Frontend Developer",
        "Backend Developer",
        "Fullstack Developer",
        "Product Designer",
        "Data Analyst",
        "Data Scientist",
        "Mobile App Developer",
        "DevOps Engineer",
        "AI Engineer",
        "Machine Learning Engineer",
        "Graphic Designer",
        "Visual Designer",
        "Creative Director",
        "Marketing Specialist",
        "Content Strategist",
        "SEO Analyst",
        "Software Engineer",
        "QA Engineer",
        "Cloud Architect",
        "Database Administrator",
        "Web Developer",
        "Technical Writer",
        "IT Support Specialist",
        "Scrum Master",
        "Project Manager",
        "Product Manager",
        "Systems Analyst",
        "Security Analyst",
        "Solutions Architect",
        "AR/VR Designer",
        "Video Editor",
        "Brand Designer",
        "Motion Designer",
        "Business Analyst",
        "Game Developer",
        "CRM Specialist",
        "eCommerce Manager",
        "Community Manager",
        "UX Researcher",
        "HR Manager",
        "Recruiter",
        "Digital Marketer",
        "Social Media Manager",
        "Creative Technologist",
        "Innovation Lead",
        "Technical Lead",
        "Customer Support Engineer",
        "Technical Account Manager",
        "Design Systems Lead",
        "Accessibility Specialist",
        "Penetration Tester",
        "Cloud Security Engineer",
        "SRE (Site Reliability Engineer)",
        "Network Engineer",
        "Blockchain Developer",
        "Embedded Systems Engineer",
        "Animation Specialist",
        "VR Developer",
        "3D Modeler",
        "Legal Consultant",
        "AI Prompt Engineer",
        "IT Auditor",
        "Cybersecurity Specialist",
        "Helpdesk Agent",
        "Platform Engineer",
        "No-code Developer",
        "Low-code Developer",
        "Game Tester",
        "Unity Developer",
        "Unreal Developer",
        "Firmware Engineer",
        "Simulation Engineer",
        "Creative Producer",
        "Growth Marketer",
        "UX Copywriter",
        "Brand Strategist",
        "Innovation Consultant",
        "Quality Assurance Tester",
        "Customer Success Manager",
        "Support Analyst",
        "Interaction Designer",
        "Storyteller",
        "Frontend Architect",
        "Digital Illustrator",
        "Infographic Designer",
        "Technical Evangelist",
        "UI Engineer",
        "API Developer",
        "Design Educator",
        "Webflow Developer",
        "Notion Specialist",
        "Chatbot Designer",
        "Prompt Designer",
        "Generative AI Designer",
        "Web3 Developer",
        "Smart Contract Developer",
        "Figma Plugin Developer",
        "AI Trainer",
        "Voice UX Designer",
        "Creative Coder",
        "Product Illustrator",
    ],
};

export const locations = {
  ghana: [
    "Accra, Ghana", "Kumasi, Ghana", "Tamale, Ghana", "Sekondi-Takoradi, Ghana", "Cape Coast, Ghana",
    "Ho, Ghana", "Sunyani, Ghana", "Koforidua, Ghana", "Wa, Ghana", "Bolgatanga, Ghana",
    "Tema, Ghana", "Obuasi, Ghana", "Techiman, Ghana", "Winneba, Ghana", "Aflao, Ghana",
    "Nkawkaw, Ghana", "Agona Swedru, Ghana", "Goaso, Ghana", "Suhum, Ghana", "Dunkwa-on-Offin, Ghana",
    "Nsawam, Ghana", "Bibiani, Ghana", "Akosombo, Ghana", "Ada Foah, Ghana", "Berekum, Ghana",
    "Bawku, Ghana", "Damongo, Ghana", "Yendi, Ghana", "Prestea, Ghana", "Tarkwa, Ghana",
    "Foso, Ghana", "Salaga, Ghana", "Wenchi, Ghana", "Konongo, Ghana", "Mampong, Ghana",
    "Keta, Ghana", "Elmina, Ghana", "Dodowa, Ghana", "Somanya, Ghana", "Kwahu Abetifi, Ghana",
    "Apam, Ghana", "Saltpond, Ghana", "Axim, Ghana", "Anloga, Ghana", "Atebubu, Ghana",
    "Ejura, Ghana", "Jasikan, Ghana", "Navrongo, Ghana", "Peki, Ghana", "Asamankese, Ghana",
    "Assin Foso, Ghana", "Kibi, Ghana", "Larteh, Ghana", "Madina, Ghana", "Dome, Ghana",
    "Ofankor, Ghana", "Prampram, Ghana", "Adenta, Ghana", "Sakumono, Ghana", "Ashaiman, Ghana",
    "Ablekuma, Ghana", "Gbawe, Ghana", "Kasoa, Ghana", "Bawaleshi, Ghana", "Lapaz, Ghana",
    "Mallam, Ghana", "Darkuman, Ghana", "Dansoman, Ghana", "Weija, Ghana", "Haatso, Ghana",
    "Kwabenya, Ghana", "East Legon, Ghana", "Cantonments, Ghana", "Labadi, Ghana", "Osu, Ghana",
    "Adabraka, Ghana", "Jamestown, Ghana", "Korle Gonno, Ghana", "Mamprobi, Ghana", "Laterbiokorshie, Ghana",
    "Kokomlemle, Ghana", "Nima, Ghana", "Maamobi, Ghana", "Roman Ridge, Ghana", "Dzorwulu, Ghana",
    "Airport Residential Area, Ghana", "Spintex, Ghana", "Tema Community 1, Ghana", "Tema Community 2, Ghana", "Tema Community 3, Ghana",
    "Tema Community 4, Ghana", "Tema Community 5, Ghana", "Tema Community 6, Ghana", "Tema Community 7, Ghana", "Tema Community 8, Ghana",
    "Tema Community 9, Ghana", "Tema Community 10, Ghana", "Tema Community 11, Ghana", "Tema Community 12, Ghana", "Tema Community 25, Ghana"
  ],
  nigeria: [
    "Lagos, Nigeria", "Abuja, Nigeria", "Kano, Nigeria", "Ibadan, Nigeria", "Port Harcourt, Nigeria",
    "Benin City, Nigeria", "Kaduna, Nigeria", "Enugu, Nigeria", "Abeokuta, Nigeria", "Maiduguri, Nigeria",
    "Zaria, Nigeria", "Jos, Nigeria", "Ilorin, Nigeria", "Warri, Nigeria", "Akure, Nigeria",
    "Aba, Nigeria", "Owerri, Nigeria", "Calabar, Nigeria", "Uyo, Nigeria", "Sokoto, Nigeria",
    "Ogbomosho, Nigeria", "Onitsha, Nigeria", "Ile-Ife, Nigeria", "Osogbo, Nigeria", "Minna, Nigeria",
    "Makurdi, Nigeria", "Bauchi, Nigeria", "Yola, Nigeria", "Lokoja, Nigeria", "Gombe, Nigeria",
    "Katsina, Nigeria", "Awka, Nigeria", "Birnin Kebbi, Nigeria", "Gusau, Nigeria", "Jalingo, Nigeria",
    "Lafia, Nigeria", "Abakaliki, Nigeria", "Umuahia, Nigeria", "Oshogbo, Nigeria", "Okene, Nigeria",
    "Sapele, Nigeria", "Bida, Nigeria", "Gwagwalada, Nigeria", "Iseyin, Nigeria", "Epe, Nigeria",
    "Badagry, Nigeria", "Ikorodu, Nigeria", "Shagamu, Nigeria", "Ijebu-Ode, Nigeria", "Suleja, Nigeria",
    "Ilesha, Nigeria", "Ado Ekiti, Nigeria", "Ondo City, Nigeria", "Effurun, Nigeria", "Keffi, Nigeria",
    "Wukari, Nigeria", "Bama, Nigeria", "Funtua, Nigeria", "Gumel, Nigeria", "Hadejia, Nigeria",
    "Jebba, Nigeria", "Kumo, Nigeria", "Kwale, Nigeria", "Mubi, Nigeria", "Nnewi, Nigeria",
    "Nsukka, Nigeria", "Okigwe, Nigeria", "Owo, Nigeria", "Pankshin, Nigeria", "Potiskum, Nigeria",
    "Rijau, Nigeria", "Rumuolumeni, Nigeria", "Shendam, Nigeria", "Ughelli, Nigeria", "Uromi, Nigeria",
    "Vom, Nigeria", "Yenagoa, Nigeria", "Zungeru, Nigeria", "Ikirun, Nigeria", "Offa, Nigeria",
    "Saki, Nigeria", "Apapa, Nigeria", "Festac Town, Nigeria", "Ikoyi, Nigeria", "Victoria Island, Nigeria",
    "Lekki, Nigeria", "Surulere, Nigeria", "Yaba, Nigeria", "Mushin, Nigeria", "Agege, Nigeria",
    "Ikeja, Nigeria", "Maryland, Nigeria", "Oshodi, Nigeria", "Mile 2, Nigeria", "Ajegunle, Nigeria",
    "Egbeda, Nigeria", "Alimosho, Nigeria", "Ketu, Nigeria", "Ojota, Nigeria", "Omole, Nigeria"
  ]
};

export const phoneNumbers = {
    ghana: [
        "0241234567",
        "0549876543",
        "0273456789",
        "0201239876",
        "0504567890",
        "0261112233",
        "0559988776",
        "0234567891",
        "0591122334",
        "0283344556",
        "0244455667",
        "0547766554",
        "0278899001",
        "0209988776",
        "0506677889",
        "0262233445",
        "0553344556",
        "0231122334",
        "0595566778",
        "0289988776",
    ],
    nigeria: [
        "+2347010000001",
        "+2348030000002",
        "+2348120000003",
        "+2349090000004",
    ],
};
